import type { Track } from "./store";

export const SEED_VERSION = "2026-06-04-v2";

export const SEED_TRACKS: Track[] = [
  {
    id: "physics",
    name: "Physics",
    chapters: [
      { id: "physics-unit-dimension", trackId: "physics", name: "Unit & Dimension", priority: "Medium", completion: 0, concepts: [
        { id: "physics-unit-dimension-c1", name: "SI units & dimensional analysis", done: false, weight: "Medium" },
        { id: "physics-unit-dimension-c2", name: "Error analysis — absolute, relative, % error", done: false, weight: "Medium" },
        { id: "physics-unit-dimension-c3", name: "Significant figures & rounding", done: false, weight: "Low" },
      ]},
      { id: "physics-basic-maths", trackId: "physics", name: "Basic Maths", priority: "Medium", completion: 0, concepts: [
        { id: "physics-basic-maths-c1", name: "Differentiation — basic rules", done: false, weight: "Medium" },
        { id: "physics-basic-maths-c2", name: "Integration — basic rules", done: false, weight: "Medium" },
        { id: "physics-basic-maths-c3", name: "Graphs — slope, area interpretation", done: false, weight: "Medium" },
        { id: "physics-basic-maths-c4", name: "Vectors — addition, subtraction, components", done: false, weight: "Medium" },
      ]},
      { id: "physics-vectors", trackId: "physics", name: "Vectors", priority: "Medium", completion: 0, concepts: [
        { id: "physics-vectors-c1", name: "Vector addition & subtraction", done: false, weight: "Medium" },
        { id: "physics-vectors-c2", name: "Dot product & cross product", done: false, weight: "Medium" },
        { id: "physics-vectors-c3", name: "Unit vector & resolution of vectors", done: false, weight: "Medium" },
      ]},
      { id: "physics-kinematics", trackId: "physics", name: "Kinematics", priority: "High", completion: 0, concepts: [
        { id: "physics-kinematics-c1", name: "Equations of motion (v, s, a)", done: false, weight: "Medium" },
        { id: "physics-kinematics-c2", name: "Projectile motion", done: false, weight: "High" },
        { id: "physics-kinematics-c3", name: "Relative velocity", done: false, weight: "Medium" },
        { id: "physics-kinematics-c4", name: "v-t and x-t graph analysis", done: false, weight: "Medium" },
      ]},
      { id: "physics-laws-of-motion", trackId: "physics", name: "Laws of Motion", priority: "High", completion: 0, concepts: [
        { id: "physics-laws-of-motion-c1", name: "Newton's three laws", done: false, weight: "High" },
        { id: "physics-laws-of-motion-c2", name: "Free body diagrams", done: false, weight: "High" },
        { id: "physics-laws-of-motion-c3", name: "Constraint motion (string/pulley)", done: false, weight: "Medium" },
        { id: "physics-laws-of-motion-c4", name: "Pseudo force in non-inertial frames", done: false, weight: "Medium" },
      ]},
      { id: "physics-friction", trackId: "physics", name: "Friction", priority: "High", completion: 0, concepts: [
        { id: "physics-friction-c1", name: "Static & kinetic friction", done: false, weight: "High" },
        { id: "physics-friction-c2", name: "Angle of friction & angle of repose", done: false, weight: "Medium" },
        { id: "physics-friction-c3", name: "Motion on rough inclined plane", done: false, weight: "Medium" },
      ]},
      { id: "physics-circular-motion", trackId: "physics", name: "Circular Motion", priority: "High", completion: 0, concepts: [
        { id: "physics-circular-motion-c1", name: "Centripetal acceleration & force", done: false, weight: "High" },
        { id: "physics-circular-motion-c2", name: "Vertical circular motion", done: false, weight: "High" },
        { id: "physics-circular-motion-c3", name: "Banking of roads", done: false, weight: "Medium" },
      ]},
      { id: "physics-work-energy-power", trackId: "physics", name: "Work Energy Power", priority: "High", completion: 0, concepts: [
        { id: "physics-work-energy-power-c1", name: "Work-energy theorem", done: false, weight: "High" },
        { id: "physics-work-energy-power-c2", name: "Conservative & non-conservative forces", done: false, weight: "Medium" },
        { id: "physics-work-energy-power-c3", name: "Potential energy & energy conservation", done: false, weight: "High" },
        { id: "physics-work-energy-power-c4", name: "Power & efficiency", done: false, weight: "Low" },
      ]},
      { id: "physics-centre-of-mass-and-momentum", trackId: "physics", name: "Centre of Mass and Momentum", priority: "High", completion: 0, concepts: [
        { id: "physics-centre-of-mass-and-momentum-c1", name: "Centre of mass of system of particles", done: false, weight: "Medium" },
        { id: "physics-centre-of-mass-and-momentum-c2", name: "Conservation of linear momentum", done: false, weight: "High" },
        { id: "physics-centre-of-mass-and-momentum-c3", name: "Elastic & inelastic collisions", done: false, weight: "High" },
        { id: "physics-centre-of-mass-and-momentum-c4", name: "Rocket propulsion", done: false, weight: "Low" },
      ]},
      { id: "physics-rotation-of-rigid-body", trackId: "physics", name: "Rotation of Rigid Body", priority: "High", completion: 0, concepts: [
        { id: "physics-rotation-of-rigid-body-c1", name: "Moment of inertia & parallel axis theorem", done: false, weight: "High" },
        { id: "physics-rotation-of-rigid-body-c2", name: "Torque and angular momentum", done: false, weight: "High" },
        { id: "physics-rotation-of-rigid-body-c3", name: "Rolling without slipping", done: false, weight: "High" },
        { id: "physics-rotation-of-rigid-body-c4", name: "Angular kinematics equations", done: false, weight: "Medium" },
        { id: "physics-rotation-of-rigid-body-c5", name: "Conservation of angular momentum", done: false, weight: "High" },
      ]},
      { id: "physics-shm", trackId: "physics", name: "SHM", priority: "High", completion: 0, concepts: [
        { id: "physics-shm-c1", name: "SHM — equation, energy, time period", done: false, weight: "High" },
        { id: "physics-shm-c2", name: "Spring-mass and pendulum systems", done: false, weight: "High" },
        { id: "physics-shm-c3", name: "Damped & forced oscillations", done: false, weight: "Medium" },
      ]},
      { id: "physics-calorimetry-thermal-expansion-and-heat-transfer", trackId: "physics", name: "Calorimetry Thermal Expansion and Heat Transfer", priority: "Medium", completion: 0, concepts: [
        { id: "physics-calorimetry-thermal-expansion-and-heat-transfer-c1", name: "Specific heat & calorimetry", done: false, weight: "Medium" },
        { id: "physics-calorimetry-thermal-expansion-and-heat-transfer-c2", name: "Linear, area & volume expansion", done: false, weight: "Medium" },
        { id: "physics-calorimetry-thermal-expansion-and-heat-transfer-c3", name: "Conduction, convection & radiation", done: false, weight: "Medium" },
        { id: "physics-calorimetry-thermal-expansion-and-heat-transfer-c4", name: "Newton's law of cooling & Stefan's law", done: false, weight: "Medium" },
      ]},
      { id: "physics-ktg-and-thermodynamics", trackId: "physics", name: "KTG and Thermodynamics", priority: "High", completion: 0, concepts: [
        { id: "physics-ktg-and-thermodynamics-c1", name: "Kinetic theory — rms speed, pressure, mean free path", done: false, weight: "High" },
        { id: "physics-ktg-and-thermodynamics-c2", name: "First law & internal energy", done: false, weight: "High" },
        { id: "physics-ktg-and-thermodynamics-c3", name: "Isothermal, adiabatic, isochoric, isobaric processes", done: false, weight: "High" },
        { id: "physics-ktg-and-thermodynamics-c4", name: "Second law & Carnot engine efficiency", done: false, weight: "High" },
        { id: "physics-ktg-and-thermodynamics-c5", name: "Specific heat of gases (Cp, Cv, γ)", done: false, weight: "Medium" },
      ]},
      { id: "physics-fluid-mechanics", trackId: "physics", name: "Fluid Mechanics", priority: "High", completion: 0, concepts: [
        { id: "physics-fluid-mechanics-c1", name: "Pressure & Pascal's law", done: false, weight: "Medium" },
        { id: "physics-fluid-mechanics-c2", name: "Archimedes' principle & buoyancy", done: false, weight: "High" },
        { id: "physics-fluid-mechanics-c3", name: "Bernoulli's equation & applications", done: false, weight: "High" },
        { id: "physics-fluid-mechanics-c4", name: "Viscosity & Stokes' law", done: false, weight: "Medium" },
        { id: "physics-fluid-mechanics-c5", name: "Surface tension & capillarity", done: false, weight: "Medium" },
      ]},
      { id: "physics-elasticity", trackId: "physics", name: "Elasticity", priority: "Medium", completion: 0, concepts: [
        { id: "physics-elasticity-c1", name: "Stress, strain & Young's modulus", done: false, weight: "High" },
        { id: "physics-elasticity-c2", name: "Bulk modulus & shear modulus", done: false, weight: "Medium" },
        { id: "physics-elasticity-c3", name: "Hooke's law & elastic potential energy", done: false, weight: "Medium" },
      ]},
      { id: "physics-wave-in-string", trackId: "physics", name: "Wave in String", priority: "High", completion: 0, concepts: [
        { id: "physics-wave-in-string-c1", name: "Wave equation & transverse waves", done: false, weight: "High" },
        { id: "physics-wave-in-string-c2", name: "Superposition & standing waves", done: false, weight: "High" },
        { id: "physics-wave-in-string-c3", name: "Harmonics in string — fundamental & overtones", done: false, weight: "High" },
      ]},
      { id: "physics-sound-wave", trackId: "physics", name: "Sound Wave", priority: "High", completion: 0, concepts: [
        { id: "physics-sound-wave-c1", name: "Speed of sound & factors affecting it", done: false, weight: "Medium" },
        { id: "physics-sound-wave-c2", name: "Beats & interference of sound", done: false, weight: "High" },
        { id: "physics-sound-wave-c3", name: "Doppler effect", done: false, weight: "High" },
        { id: "physics-sound-wave-c4", name: "Resonance in pipes (open & closed)", done: false, weight: "High" },
      ]},
      { id: "physics-gravitation", trackId: "physics", name: "Gravitation", priority: "High", completion: 0, concepts: [
        { id: "physics-gravitation-c1", name: "Newton's law of gravitation", done: false, weight: "High" },
        { id: "physics-gravitation-c2", name: "Gravitational field & potential", done: false, weight: "High" },
        { id: "physics-gravitation-c3", name: "Kepler's laws", done: false, weight: "High" },
        { id: "physics-gravitation-c4", name: "Orbital & escape velocity", done: false, weight: "High" },
        { id: "physics-gravitation-c5", name: "Geostationary satellites & binding energy", done: false, weight: "Medium" },
      ]},
      { id: "physics-electrostatics", trackId: "physics", name: "Electrostatics", priority: "High", completion: 0, concepts: [
        { id: "physics-electrostatics-c1", name: "Coulomb's law & superposition", done: false, weight: "High" },
        { id: "physics-electrostatics-c2", name: "Electric field & flux", done: false, weight: "High" },
        { id: "physics-electrostatics-c3", name: "Gauss's law applications", done: false, weight: "High" },
        { id: "physics-electrostatics-c4", name: "Electric potential & potential energy", done: false, weight: "High" },
        { id: "physics-electrostatics-c5", name: "Conductors & dielectrics", done: false, weight: "Medium" },
      ]},
      { id: "physics-capacitance", trackId: "physics", name: "Capacitance", priority: "High", completion: 0, concepts: [
        { id: "physics-capacitance-c1", name: "Capacitor — parallel plate, energy stored", done: false, weight: "High" },
        { id: "physics-capacitance-c2", name: "Series & parallel combination", done: false, weight: "High" },
        { id: "physics-capacitance-c3", name: "Dielectric — capacitance & energy effect", done: false, weight: "Medium" },
        { id: "physics-capacitance-c4", name: "Charging & discharging of RC circuit", done: false, weight: "High" },
      ]},
      { id: "physics-current-electricity", trackId: "physics", name: "Current Electricity", priority: "High", completion: 0, concepts: [
        { id: "physics-current-electricity-c1", name: "Ohm's law & resistivity", done: false, weight: "High" },
        { id: "physics-current-electricity-c2", name: "Kirchhoff's laws (KVL, KCL)", done: false, weight: "High" },
        { id: "physics-current-electricity-c3", name: "Wheatstone bridge & meter bridge", done: false, weight: "High" },
        { id: "physics-current-electricity-c4", name: "EMF & internal resistance", done: false, weight: "High" },
        { id: "physics-current-electricity-c5", name: "Potentiometer", done: false, weight: "Medium" },
      ]},
      { id: "physics-magnetic-effect-of-current", trackId: "physics", name: "Magnetic Effect of Current", priority: "High", completion: 0, concepts: [
        { id: "physics-magnetic-effect-of-current-c1", name: "Biot-Savart law", done: false, weight: "High" },
        { id: "physics-magnetic-effect-of-current-c2", name: "Ampere's law applications", done: false, weight: "High" },
        { id: "physics-magnetic-effect-of-current-c3", name: "Force on current-carrying conductor & moving charge", done: false, weight: "High" },
        { id: "physics-magnetic-effect-of-current-c4", name: "Galvanometer — ammeter & voltmeter conversion", done: false, weight: "Medium" },
      ]},
      { id: "physics-magnetic-properties", trackId: "physics", name: "Magnetic Properties", priority: "Medium", completion: 0, concepts: [
        { id: "physics-magnetic-properties-c1", name: "Diamagnetic, paramagnetic, ferromagnetic", done: false, weight: "Medium" },
        { id: "physics-magnetic-properties-c2", name: "Bar magnet — field, potential", done: false, weight: "Medium" },
        { id: "physics-magnetic-properties-c3", name: "Earth's magnetism & declination", done: false, weight: "Low" },
      ]},
      { id: "physics-emi", trackId: "physics", name: "EMI", priority: "High", completion: 0, concepts: [
        { id: "physics-emi-c1", name: "Faraday's & Lenz's law", done: false, weight: "High" },
        { id: "physics-emi-c2", name: "Self & mutual inductance", done: false, weight: "High" },
        { id: "physics-emi-c3", name: "Eddy currents & motional EMF", done: false, weight: "Medium" },
      ]},
      { id: "physics-ac", trackId: "physics", name: "A.C.", priority: "High", completion: 0, concepts: [
        { id: "physics-ac-c1", name: "Phasor diagrams — R, L, C circuits", done: false, weight: "High" },
        { id: "physics-ac-c2", name: "LCR series resonance", done: false, weight: "High" },
        { id: "physics-ac-c3", name: "Power in AC & power factor", done: false, weight: "Medium" },
        { id: "physics-ac-c4", name: "Transformer — step-up & step-down", done: false, weight: "Medium" },
      ]},
      { id: "physics-geometrical-optics", trackId: "physics", name: "Geometrical Optics", priority: "High", completion: 0, concepts: [
        { id: "physics-geometrical-optics-c1", name: "Reflection — mirrors & image formation", done: false, weight: "High" },
        { id: "physics-geometrical-optics-c2", name: "Refraction — Snell's law, TIR, critical angle", done: false, weight: "High" },
        { id: "physics-geometrical-optics-c3", name: "Lens formula, magnification & lens maker's equation", done: false, weight: "High" },
        { id: "physics-geometrical-optics-c4", name: "Prism — deviation & dispersion", done: false, weight: "High" },
        { id: "physics-geometrical-optics-c5", name: "Optical instruments — microscope & telescope", done: false, weight: "Medium" },
      ]},
      { id: "physics-wave-optics", trackId: "physics", name: "Wave Optics", priority: "High", completion: 0, concepts: [
        { id: "physics-wave-optics-c1", name: "Huygens' principle & wavefronts", done: false, weight: "Medium" },
        { id: "physics-wave-optics-c2", name: "Young's double slit experiment (YDSE)", done: false, weight: "High" },
        { id: "physics-wave-optics-c3", name: "Diffraction — single slit pattern", done: false, weight: "High" },
        { id: "physics-wave-optics-c4", name: "Polarisation — Brewster's law, Malus's law", done: false, weight: "Medium" },
      ]},
      { id: "physics-em-waves", trackId: "physics", name: "EM Waves", priority: "Medium", completion: 0, concepts: [
        { id: "physics-em-waves-c1", name: "Maxwell's equations & displacement current", done: false, weight: "Medium" },
        { id: "physics-em-waves-c2", name: "EM spectrum — frequencies & wavelengths", done: false, weight: "Medium" },
        { id: "physics-em-waves-c3", name: "Energy & momentum of EM wave", done: false, weight: "Low" },
      ]},
      { id: "physics-modern-physics-1", trackId: "physics", name: "Modern Physics 1", priority: "High", completion: 0, concepts: [
        { id: "physics-modern-physics-1-c1", name: "Photoelectric effect — Einstein's equation", done: false, weight: "High" },
        { id: "physics-modern-physics-1-c2", name: "de Broglie wavelength & matter waves", done: false, weight: "High" },
        { id: "physics-modern-physics-1-c3", name: "X-rays — production & Moseley's law", done: false, weight: "Medium" },
      ]},
      { id: "physics-atomic-structure", trackId: "physics", name: "Atomic Structure", priority: "High", completion: 0, concepts: [
        { id: "physics-atomic-structure-c1", name: "Bohr model — energy levels & spectral lines", done: false, weight: "High" },
        { id: "physics-atomic-structure-c2", name: "Hydrogen spectrum — Lyman, Balmer, Paschen series", done: false, weight: "High" },
        { id: "physics-atomic-structure-c3", name: "Thomson & Rutherford models", done: false, weight: "Low" },
      ]},
      { id: "physics-nuclear-physics", trackId: "physics", name: "Nuclear Physics", priority: "High", completion: 0, concepts: [
        { id: "physics-nuclear-physics-c1", name: "Radioactivity — α, β, γ decay", done: false, weight: "High" },
        { id: "physics-nuclear-physics-c2", name: "Radioactive decay law & half-life", done: false, weight: "High" },
        { id: "physics-nuclear-physics-c3", name: "Binding energy per nucleon & mass defect", done: false, weight: "High" },
        { id: "physics-nuclear-physics-c4", name: "Nuclear fission & fusion", done: false, weight: "Medium" },
      ]},
      { id: "physics-semiconductor", trackId: "physics", name: "Semiconductor", priority: "High", completion: 0, concepts: [
        { id: "physics-semiconductor-c1", name: "Energy bands — conductor, insulator, semiconductor", done: false, weight: "Medium" },
        { id: "physics-semiconductor-c2", name: "p-n junction diode & I-V characteristics", done: false, weight: "High" },
        { id: "physics-semiconductor-c3", name: "Rectifier circuits — half wave & full wave", done: false, weight: "Medium" },
        { id: "physics-semiconductor-c4", name: "Transistor — CE configuration & logic gates", done: false, weight: "High" },
      ]},
    ],
  },
  {
    id: "pchem",
    name: "Physical Chemistry",
    chapters: [
      { id: "pchem-mole-concept", trackId: "pchem", name: "Mole Concept", priority: "High", completion: 0, concepts: [
        { id: "pchem-mole-concept-c1", name: "Mole, Avogadro number, molar mass", done: false, weight: "High" },
        { id: "pchem-mole-concept-c2", name: "Stoichiometry & balancing equations", done: false, weight: "High" },
        { id: "pchem-mole-concept-c3", name: "Limiting reagent & % yield", done: false, weight: "High" },
        { id: "pchem-mole-concept-c4", name: "Concentration terms (M, m, χ, ppm)", done: false, weight: "Medium" },
        { id: "pchem-mole-concept-c5", name: "POAC & cross-multiplication method", done: false, weight: "Medium" },
      ]},
      { id: "pchem-atomic-structure", trackId: "pchem", name: "Atomic Structure", priority: "High", completion: 0, concepts: [
        { id: "pchem-atomic-structure-c1", name: "Bohr model & spectral lines", done: false, weight: "High" },
        { id: "pchem-atomic-structure-c2", name: "Quantum numbers (n, l, m, s)", done: false, weight: "High" },
        { id: "pchem-atomic-structure-c3", name: "Orbital shapes & radial nodes", done: false, weight: "High" },
        { id: "pchem-atomic-structure-c4", name: "Electronic configuration & exceptions (Cr, Cu)", done: false, weight: "High" },
        { id: "pchem-atomic-structure-c5", name: "de Broglie & Heisenberg uncertainty principle", done: false, weight: "Medium" },
      ]},
      { id: "pchem-gaseous-state", trackId: "pchem", name: "Gaseous State", priority: "High", completion: 0, concepts: [
        { id: "pchem-gaseous-state-c1", name: "Gas laws — Boyle's, Charles', Avogadro's", done: false, weight: "High" },
        { id: "pchem-gaseous-state-c2", name: "Ideal gas equation & Graham's law", done: false, weight: "High" },
        { id: "pchem-gaseous-state-c3", name: "KTG — rms, average, most probable speed", done: false, weight: "High" },
        { id: "pchem-gaseous-state-c4", name: "van der Waals equation & real gases", done: false, weight: "High" },
        { id: "pchem-gaseous-state-c5", name: "Compressibility factor & Boyle temperature", done: false, weight: "Medium" },
      ]},
      { id: "pchem-redox-reactions", trackId: "pchem", name: "Redox Reactions", priority: "High", completion: 0, concepts: [
        { id: "pchem-redox-reactions-c1", name: "Oxidation number rules & change method", done: false, weight: "High" },
        { id: "pchem-redox-reactions-c2", name: "Balancing redox — half-reaction method", done: false, weight: "High" },
        { id: "pchem-redox-reactions-c3", name: "Disproportionation reactions", done: false, weight: "Medium" },
      ]},
      { id: "pchem-thermodynamics", trackId: "pchem", name: "Thermodynamics", priority: "High", completion: 0, concepts: [
        { id: "pchem-thermodynamics-c1", name: "System, surroundings, state functions", done: false, weight: "High" },
        { id: "pchem-thermodynamics-c2", name: "Enthalpy & Hess's law", done: false, weight: "High" },
        { id: "pchem-thermodynamics-c3", name: "Entropy & second law", done: false, weight: "High" },
        { id: "pchem-thermodynamics-c4", name: "Gibbs free energy & spontaneity", done: false, weight: "High" },
        { id: "pchem-thermodynamics-c5", name: "Bond enthalpies & Born-Haber cycle", done: false, weight: "High" },
      ]},
      { id: "pchem-thermochemistry", trackId: "pchem", name: "Thermochemistry", priority: "High", completion: 0, concepts: [
        { id: "pchem-thermochemistry-c1", name: "Enthalpy of formation, combustion, neutralisation", done: false, weight: "High" },
        { id: "pchem-thermochemistry-c2", name: "Hess's law calculations", done: false, weight: "High" },
        { id: "pchem-thermochemistry-c3", name: "Kirchhoff's equation", done: false, weight: "Medium" },
      ]},
      { id: "pchem-chemical-equilibrium", trackId: "pchem", name: "Chemical Equilibrium", priority: "High", completion: 0, concepts: [
        { id: "pchem-chemical-equilibrium-c1", name: "Kc and Kp expressions", done: false, weight: "High" },
        { id: "pchem-chemical-equilibrium-c2", name: "Relation between Kc and Kp", done: false, weight: "High" },
        { id: "pchem-chemical-equilibrium-c3", name: "Le Chatelier's principle", done: false, weight: "High" },
        { id: "pchem-chemical-equilibrium-c4", name: "Degree of dissociation calculations", done: false, weight: "High" },
      ]},
      { id: "pchem-ionic-equilibrium", trackId: "pchem", name: "Ionic Equilibrium", priority: "High", completion: 0, concepts: [
        { id: "pchem-ionic-equilibrium-c1", name: "pH, pOH, pKa, pKb", done: false, weight: "High" },
        { id: "pchem-ionic-equilibrium-c2", name: "Buffer solutions (Henderson equation)", done: false, weight: "High" },
        { id: "pchem-ionic-equilibrium-c3", name: "Solubility product (Ksp)", done: false, weight: "High" },
        { id: "pchem-ionic-equilibrium-c4", name: "Salt hydrolysis", done: false, weight: "High" },
        { id: "pchem-ionic-equilibrium-c5", name: "Indicators & titration curves", done: false, weight: "Medium" },
      ]},
      { id: "pchem-electrochemistry", trackId: "pchem", name: "Electrochemistry", priority: "High", completion: 0, concepts: [
        { id: "pchem-electrochemistry-c1", name: "Galvanic cell, EMF, SHE", done: false, weight: "High" },
        { id: "pchem-electrochemistry-c2", name: "Nernst equation", done: false, weight: "High" },
        { id: "pchem-electrochemistry-c3", name: "Electrolysis & Faraday's laws", done: false, weight: "High" },
        { id: "pchem-electrochemistry-c4", name: "Conductance & Kohlrausch's law", done: false, weight: "Medium" },
      ]},
      { id: "pchem-chemical-kinetics", trackId: "pchem", name: "Chemical Kinetics", priority: "High", completion: 0, concepts: [
        { id: "pchem-chemical-kinetics-c1", name: "Rate laws & order of reaction", done: false, weight: "High" },
        { id: "pchem-chemical-kinetics-c2", name: "Integrated rate equations (0, 1st, 2nd order)", done: false, weight: "High" },
        { id: "pchem-chemical-kinetics-c3", name: "Arrhenius equation & activation energy", done: false, weight: "High" },
        { id: "pchem-chemical-kinetics-c4", name: "Half-life calculations", done: false, weight: "High" },
        { id: "pchem-chemical-kinetics-c5", name: "Catalysis — homogeneous & heterogeneous", done: false, weight: "Medium" },
      ]},
      { id: "pchem-solutions", trackId: "pchem", name: "Solutions", priority: "High", completion: 0, concepts: [
        { id: "pchem-solutions-c1", name: "Raoult's law & ideal/non-ideal solutions", done: false, weight: "High" },
        { id: "pchem-solutions-c2", name: "Elevation of boiling point & depression of freezing point", done: false, weight: "High" },
        { id: "pchem-solutions-c3", name: "Osmosis & van't Hoff factor", done: false, weight: "High" },
        { id: "pchem-solutions-c4", name: "Henry's law & solubility of gases", done: false, weight: "Medium" },
      ]},
      { id: "pchem-solid-state", trackId: "pchem", name: "Solid State", priority: "High", completion: 0, concepts: [
        { id: "pchem-solid-state-c1", name: "Crystal systems & unit cell", done: false, weight: "High" },
        { id: "pchem-solid-state-c2", name: "Packing efficiency — BCC, FCC, HCP", done: false, weight: "High" },
        { id: "pchem-solid-state-c3", name: "Radius ratio & ionic crystals", done: false, weight: "High" },
        { id: "pchem-solid-state-c4", name: "Defects — Schottky, Frenkel, interstitial", done: false, weight: "High" },
      ]},
      { id: "pchem-surface-chemistry", trackId: "pchem", name: "Surface Chemistry", priority: "Medium", completion: 0, concepts: [
        { id: "pchem-surface-chemistry-c1", name: "Adsorption — physisorption vs chemisorption", done: false, weight: "High" },
        { id: "pchem-surface-chemistry-c2", name: "Freundlich & Langmuir isotherms", done: false, weight: "Medium" },
        { id: "pchem-surface-chemistry-c3", name: "Colloids — types, Tyndall effect, Brownian motion", done: false, weight: "High" },
        { id: "pchem-surface-chemistry-c4", name: "Emulsions, gels & coagulation", done: false, weight: "Medium" },
      ]},
    ],
  },
  {
    id: "ochem",
    name: "Organic Chemistry",
    chapters: [
      { id: "ochem-iupac-nomenclature", trackId: "ochem", name: "IUPAC Nomenclature", priority: "High", completion: 0, concepts: [
        { id: "ochem-iupac-nomenclature-c1", name: "IUPAC naming of alkanes, alkenes, alkynes", done: false, weight: "High" },
        { id: "ochem-iupac-nomenclature-c2", name: "Naming of substituted compounds", done: false, weight: "High" },
        { id: "ochem-iupac-nomenclature-c3", name: "Priority rules for functional groups", done: false, weight: "High" },
      ]},
      { id: "ochem-goc", trackId: "ochem", name: "GOC", priority: "High", completion: 0, concepts: [
        { id: "ochem-goc-c1", name: "Inductive & field effects", done: false, weight: "High" },
        { id: "ochem-goc-c2", name: "Resonance & mesomeric effect", done: false, weight: "High" },
        { id: "ochem-goc-c3", name: "Hyperconjugation", done: false, weight: "High" },
        { id: "ochem-goc-c4", name: "Carbocation, carbanion, free radical stability", done: false, weight: "High" },
        { id: "ochem-goc-c5", name: "Reaction intermediates — types & stability", done: false, weight: "High" },
      ]},
      { id: "ochem-isomerism", trackId: "ochem", name: "Isomerism", priority: "High", completion: 0, concepts: [
        { id: "ochem-isomerism-c1", name: "Structural isomerism — chain, position, functional", done: false, weight: "High" },
        { id: "ochem-isomerism-c2", name: "Geometrical isomerism (E/Z, cis/trans)", done: false, weight: "High" },
        { id: "ochem-isomerism-c3", name: "Optical isomerism — chirality, R/S configuration", done: false, weight: "High" },
        { id: "ochem-isomerism-c4", name: "Conformational isomerism", done: false, weight: "Medium" },
      ]},
      { id: "ochem-hydrocarbons", trackId: "ochem", name: "Hydrocarbons", priority: "High", completion: 0, concepts: [
        { id: "ochem-hydrocarbons-c1", name: "Alkanes — free radical halogenation", done: false, weight: "High" },
        { id: "ochem-hydrocarbons-c2", name: "Alkenes — addition reactions, Markovnikov", done: false, weight: "High" },
        { id: "ochem-hydrocarbons-c3", name: "Alkynes — acidic nature, reactions", done: false, weight: "High" },
        { id: "ochem-hydrocarbons-c4", name: "Aromatic compounds — EAS & directing effects", done: false, weight: "High" },
        { id: "ochem-hydrocarbons-c5", name: "Birch reduction & Friedel-Crafts", done: false, weight: "High" },
      ]},
      { id: "ochem-haloalkanes-haloarenes", trackId: "ochem", name: "Haloalkanes & Haloarenes", priority: "High", completion: 0, concepts: [
        { id: "ochem-haloalkanes-haloarenes-c1", name: "SN1 vs SN2 mechanism", done: false, weight: "High" },
        { id: "ochem-haloalkanes-haloarenes-c2", name: "E1 vs E2 elimination", done: false, weight: "High" },
        { id: "ochem-haloalkanes-haloarenes-c3", name: "Nucleophilic aromatic substitution", done: false, weight: "Medium" },
        { id: "ochem-haloalkanes-haloarenes-c4", name: "Grignard reagent preparation & reactions", done: false, weight: "High" },
      ]},
      { id: "ochem-alcohols-phenols-ethers", trackId: "ochem", name: "Alcohols, Phenols, Ethers", priority: "High", completion: 0, concepts: [
        { id: "ochem-alcohols-phenols-ethers-c1", name: "Acidity of alcohols vs phenols", done: false, weight: "High" },
        { id: "ochem-alcohols-phenols-ethers-c2", name: "Reactions of alcohols (oxidation, esterification)", done: false, weight: "High" },
        { id: "ochem-alcohols-phenols-ethers-c3", name: "Phenol reactions (Kolbe, Reimer-Tiemann, coupling)", done: false, weight: "High" },
        { id: "ochem-alcohols-phenols-ethers-c4", name: "Ether synthesis (Williamson) & cleavage", done: false, weight: "High" },
      ]},
      { id: "ochem-aldehyde-ketone", trackId: "ochem", name: "Aldehyde & Ketone", priority: "High", completion: 0, concepts: [
        { id: "ochem-aldehyde-ketone-c1", name: "Nucleophilic addition mechanism", done: false, weight: "High" },
        { id: "ochem-aldehyde-ketone-c2", name: "Aldol condensation", done: false, weight: "High" },
        { id: "ochem-aldehyde-ketone-c3", name: "Cannizzaro reaction", done: false, weight: "High" },
        { id: "ochem-aldehyde-ketone-c4", name: "Oxidation — Tollens, Fehling, Benedict", done: false, weight: "High" },
        { id: "ochem-aldehyde-ketone-c5", name: "Clemmensen & Wolff-Kishner reduction", done: false, weight: "High" },
      ]},
      { id: "ochem-carboxylic-acid-derivatives", trackId: "ochem", name: "Carboxylic Acid & Derivatives", priority: "High", completion: 0, concepts: [
        { id: "ochem-carboxylic-acid-derivatives-c1", name: "Acidity factors & pKa comparison", done: false, weight: "High" },
        { id: "ochem-carboxylic-acid-derivatives-c2", name: "Fischer esterification", done: false, weight: "High" },
        { id: "ochem-carboxylic-acid-derivatives-c3", name: "Acid chlorides, anhydrides, amides", done: false, weight: "High" },
        { id: "ochem-carboxylic-acid-derivatives-c4", name: "Hell-Volhard-Zelinsky reaction", done: false, weight: "Medium" },
      ]},
      { id: "ochem-amines", trackId: "ochem", name: "Amines", priority: "High", completion: 0, concepts: [
        { id: "ochem-amines-c1", name: "Basicity order of amines", done: false, weight: "High" },
        { id: "ochem-amines-c2", name: "Preparation — Gabriel, Hoffman, reductive amination", done: false, weight: "High" },
        { id: "ochem-amines-c3", name: "Diazotization & Sandmeyer reaction", done: false, weight: "High" },
        { id: "ochem-amines-c4", name: "Coupling reaction & azo dyes", done: false, weight: "High" },
      ]},
      { id: "ochem-named-reactions", trackId: "ochem", name: "Named Reactions", priority: "High", completion: 0, concepts: [
        { id: "ochem-named-reactions-c1", name: "Aldol, Cannizzaro, Reformatsky, Perkin", done: false, weight: "High" },
        { id: "ochem-named-reactions-c2", name: "Diels-Alder, Beckmann, Baeyer-Villiger", done: false, weight: "High" },
        { id: "ochem-named-reactions-c3", name: "Clemmensen, Wolff-Kishner, Meerwein-Ponndorf", done: false, weight: "Medium" },
      ]},
      { id: "ochem-biomolecules", trackId: "ochem", name: "Biomolecules", priority: "Medium", completion: 0, concepts: [
        { id: "ochem-biomolecules-c1", name: "Carbohydrates — reducing sugars, mutarotation", done: false, weight: "High" },
        { id: "ochem-biomolecules-c2", name: "Proteins — primary to quaternary structure", done: false, weight: "High" },
        { id: "ochem-biomolecules-c3", name: "Nucleic acids — DNA vs RNA structure", done: false, weight: "Medium" },
        { id: "ochem-biomolecules-c4", name: "Vitamins, enzymes & hormones overview", done: false, weight: "Low" },
      ]},
      { id: "ochem-polymers", trackId: "ochem", name: "Polymers", priority: "Medium", completion: 0, concepts: [
        { id: "ochem-polymers-c1", name: "Addition polymers — polyethylene, PVC, Teflon", done: false, weight: "High" },
        { id: "ochem-polymers-c2", name: "Condensation polymers — nylon, Dacron, Bakelite", done: false, weight: "High" },
        { id: "ochem-polymers-c3", name: "Natural & synthetic rubber", done: false, weight: "Medium" },
      ]},
      { id: "ochem-chemistry-in-everyday-life", trackId: "ochem", name: "Chemistry in Everyday Life", priority: "Low", completion: 0, concepts: [
        { id: "ochem-chemistry-in-everyday-life-c1", name: "Drugs — analgesics, antiseptics, antibiotics", done: false, weight: "Medium" },
        { id: "ochem-chemistry-in-everyday-life-c2", name: "Soaps, detergents & cleansing action", done: false, weight: "Medium" },
        { id: "ochem-chemistry-in-everyday-life-c3", name: "Food preservatives, artificial sweeteners", done: false, weight: "Low" },
      ]},
      { id: "ochem-poc", trackId: "ochem", name: "POC", priority: "Medium", completion: 0, concepts: [
        { id: "ochem-poc-c1", name: "Elemental detection (Lassaigne's test)", done: false, weight: "Medium" },
        { id: "ochem-poc-c2", name: "Functional group identification tests", done: false, weight: "High" },
        { id: "ochem-poc-c3", name: "Purification techniques — distillation, crystallisation", done: false, weight: "Low" },
      ]},
    ],
  },
  {
    id: "ichem",
    name: "Inorganic Chemistry",
    chapters: [
      { id: "ichem-quantum-numbers-electronic-configuration", trackId: "ichem", name: "Quantum Numbers, Electronic Configuration", priority: "High", completion: 0, concepts: [
        { id: "ichem-quantum-numbers-electronic-configuration-c1", name: "Quantum numbers — n, l, m, s & their significance", done: false, weight: "High" },
        { id: "ichem-quantum-numbers-electronic-configuration-c2", name: "Aufbau principle, Hund's rule, Pauli exclusion", done: false, weight: "High" },
        { id: "ichem-quantum-numbers-electronic-configuration-c3", name: "Electronic configuration of elements & ions", done: false, weight: "High" },
      ]},
      { id: "ichem-periodic-table-periodic-properties", trackId: "ichem", name: "Periodic Table & Periodic Properties", priority: "High", completion: 0, concepts: [
        { id: "ichem-periodic-table-periodic-properties-c1", name: "Atomic & ionic radius trends", done: false, weight: "High" },
        { id: "ichem-periodic-table-periodic-properties-c2", name: "Ionization energy & electron affinity", done: false, weight: "High" },
        { id: "ichem-periodic-table-periodic-properties-c3", name: "Electronegativity & metallic character trends", done: false, weight: "High" },
        { id: "ichem-periodic-table-periodic-properties-c4", name: "Effective nuclear charge & Slater's rules", done: false, weight: "Medium" },
      ]},
      { id: "ichem-chemical-bonding-basic", trackId: "ichem", name: "Chemical Bonding (Basic)", priority: "High", completion: 0, concepts: [
        { id: "ichem-chemical-bonding-basic-c1", name: "Lewis dot structures & formal charge", done: false, weight: "High" },
        { id: "ichem-chemical-bonding-basic-c2", name: "VSEPR theory & geometry prediction", done: false, weight: "High" },
        { id: "ichem-chemical-bonding-basic-c3", name: "Hybridization (sp, sp2, sp3, sp3d…)", done: false, weight: "High" },
        { id: "ichem-chemical-bonding-basic-c4", name: "Hydrogen bonding & van der Waals forces", done: false, weight: "High" },
      ]},
      { id: "ichem-chemical-bonding-12th", trackId: "ichem", name: "Chemical Bonding 12th", priority: "High", completion: 0, concepts: [
        { id: "ichem-chemical-bonding-12th-c1", name: "Molecular orbital theory (MOT) — bonding vs antibonding", done: false, weight: "High" },
        { id: "ichem-chemical-bonding-12th-c2", name: "Bond order & magnetic properties from MOT", done: false, weight: "High" },
        { id: "ichem-chemical-bonding-12th-c3", name: "Resonance structures & resonance energy", done: false, weight: "Medium" },
      ]},
      { id: "ichem-hydrogen", trackId: "ichem", name: "Hydrogen", priority: "Medium", completion: 0, concepts: [
        { id: "ichem-hydrogen-c1", name: "Isotopes of hydrogen — protium, deuterium, tritium", done: false, weight: "Medium" },
        { id: "ichem-hydrogen-c2", name: "H₂O₂ — preparation, properties & uses", done: false, weight: "High" },
        { id: "ichem-hydrogen-c3", name: "Heavy water & hydrides (ionic, covalent, metallic)", done: false, weight: "Medium" },
      ]},
      { id: "ichem-s-block-elements", trackId: "ichem", name: "s-Block Elements", priority: "High", completion: 0, concepts: [
        { id: "ichem-s-block-elements-c1", name: "Alkali metals — properties & compounds (NaOH, Na₂CO₃)", done: false, weight: "High" },
        { id: "ichem-s-block-elements-c2", name: "Alkaline earth metals — properties & compounds (CaO, CaCO₃)", done: false, weight: "High" },
        { id: "ichem-s-block-elements-c3", name: "Anomalous behaviour of Li & Be", done: false, weight: "Medium" },
        { id: "ichem-s-block-elements-c4", name: "Biological importance of Na, K, Ca, Mg", done: false, weight: "Low" },
      ]},
      { id: "ichem-p-block-elements", trackId: "ichem", name: "p-Block Elements", priority: "High", completion: 0, concepts: [
        { id: "ichem-p-block-elements-c1", name: "Group 13 — Boron compounds (borax, boric acid, diborane)", done: false, weight: "High" },
        { id: "ichem-p-block-elements-c2", name: "Group 14 — Carbon allotropes, CO₂, silicates", done: false, weight: "High" },
        { id: "ichem-p-block-elements-c3", name: "Group 15 — Nitrogen oxides, phosphorus acids, NH₃, HNO₃", done: false, weight: "High" },
        { id: "ichem-p-block-elements-c4", name: "Group 16 — Ozone, SO₂, H₂SO₄ (contact process)", done: false, weight: "High" },
        { id: "ichem-p-block-elements-c5", name: "Group 17 — Halogens, HCl, interhalogen compounds", done: false, weight: "High" },
        { id: "ichem-p-block-elements-c6", name: "Group 18 — Noble gases & xenon compounds", done: false, weight: "Medium" },
      ]},
      { id: "ichem-d-f-block-elements", trackId: "ichem", name: "d & f-Block Elements", priority: "High", completion: 0, concepts: [
        { id: "ichem-d-f-block-elements-c1", name: "General properties & electronic configuration of transition metals", done: false, weight: "High" },
        { id: "ichem-d-f-block-elements-c2", name: "Magnetic moment & colour of transition metal compounds", done: false, weight: "High" },
        { id: "ichem-d-f-block-elements-c3", name: "Important compounds — KMnO₄, K₂Cr₂O₇ & their reactions", done: false, weight: "High" },
        { id: "ichem-d-f-block-elements-c4", name: "Lanthanide contraction & actinides", done: false, weight: "Medium" },
      ]},
      { id: "ichem-coordination-compounds", trackId: "ichem", name: "Coordination Compounds", priority: "High", completion: 0, concepts: [
        { id: "ichem-coordination-compounds-c1", name: "IUPAC nomenclature", done: false, weight: "High" },
        { id: "ichem-coordination-compounds-c2", name: "VBT & CFT bonding theories", done: false, weight: "High" },
        { id: "ichem-coordination-compounds-c3", name: "Isomerism — geometric, optical, linkage, ionisation", done: false, weight: "High" },
        { id: "ichem-coordination-compounds-c4", name: "Spectrochemical series & colour", done: false, weight: "High" },
        { id: "ichem-coordination-compounds-c5", name: "Stability constants & chelate effect", done: false, weight: "Medium" },
      ]},
      { id: "ichem-metallurgy", trackId: "ichem", name: "Metallurgy", priority: "High", completion: 0, concepts: [
        { id: "ichem-metallurgy-c1", name: "Concentration of ores — froth flotation, magnetic separation", done: false, weight: "High" },
        { id: "ichem-metallurgy-c2", name: "Reduction — thermite, carbon, hydrogen, electrolytic", done: false, weight: "High" },
        { id: "ichem-metallurgy-c3", name: "Refining — van Arkel, zone refining, distillation", done: false, weight: "Medium" },
        { id: "ichem-metallurgy-c4", name: "Ellingham diagram", done: false, weight: "High" },
      ]},
      { id: "ichem-salt-analysis", trackId: "ichem", name: "Salt Analysis", priority: "High", completion: 0, concepts: [
        { id: "ichem-salt-analysis-c1", name: "Cation identification — Groups I to VI", done: false, weight: "High" },
        { id: "ichem-salt-analysis-c2", name: "Anion tests — carbonate, sulphate, halides, nitrate", done: false, weight: "High" },
        { id: "ichem-salt-analysis-c3", name: "Flame test & characteristic colours", done: false, weight: "Medium" },
      ]},
      { id: "ichem-environmental-chemistry", trackId: "ichem", name: "Environmental Chemistry", priority: "Low", completion: 0, concepts: [
        { id: "ichem-environmental-chemistry-c1", name: "Troposphere & stratosphere pollutants", done: false, weight: "Medium" },
        { id: "ichem-environmental-chemistry-c2", name: "Ozone depletion, greenhouse effect, acid rain", done: false, weight: "Medium" },
        { id: "ichem-environmental-chemistry-c3", name: "Water & soil pollution", done: false, weight: "Low" },
      ]},
    ],
  },
  {
    id: "maths",
    name: "Mathematics",
    chapters: [
      { id: "maths-basic-calculus-and-graphs", trackId: "maths", name: "Basic Calculus and Graphs", priority: "High", completion: 0, concepts: [
        { id: "maths-basic-calculus-and-graphs-c1", name: "Basic differentiation & integration rules", done: false, weight: "High" },
        { id: "maths-basic-calculus-and-graphs-c2", name: "Graph sketching — modulus, floor, trig", done: false, weight: "High" },
        { id: "maths-basic-calculus-and-graphs-c3", name: "Transformations of graphs", done: false, weight: "Medium" },
      ]},
      { id: "maths-logarithm", trackId: "maths", name: "Logarithm", priority: "High", completion: 0, concepts: [
        { id: "maths-logarithm-c1", name: "Laws of logarithm", done: false, weight: "High" },
        { id: "maths-logarithm-c2", name: "Change of base & natural logarithm", done: false, weight: "High" },
        { id: "maths-logarithm-c3", name: "Logarithmic equations & inequalities", done: false, weight: "High" },
      ]},
      { id: "maths-sets-inequality-and-modulus", trackId: "maths", name: "Sets, Inequality and Modulus", priority: "High", completion: 0, concepts: [
        { id: "maths-sets-inequality-and-modulus-c1", name: "Set operations — union, intersection, complement", done: false, weight: "Medium" },
        { id: "maths-sets-inequality-and-modulus-c2", name: "Wavy curve method for inequalities", done: false, weight: "High" },
        { id: "maths-sets-inequality-and-modulus-c3", name: "Modulus equations & inequalities", done: false, weight: "High" },
      ]},
      { id: "maths-compound-angles", trackId: "maths", name: "Compound Angles", priority: "High", completion: 0, concepts: [
        { id: "maths-compound-angles-c1", name: "Sum & difference formulas (sin, cos, tan)", done: false, weight: "High" },
        { id: "maths-compound-angles-c2", name: "Double angle & half angle formulas", done: false, weight: "High" },
        { id: "maths-compound-angles-c3", name: "Product-to-sum & sum-to-product formulas", done: false, weight: "High" },
      ]},
      { id: "maths-quadratic-equation-and-inequalities", trackId: "maths", name: "Quadratic Equation and Inequalities", priority: "High", completion: 0, concepts: [
        { id: "maths-quadratic-equation-and-inequalities-c1", name: "Sum & product of roots (Vieta's formulas)", done: false, weight: "High" },
        { id: "maths-quadratic-equation-and-inequalities-c2", name: "Nature of roots — discriminant", done: false, weight: "High" },
        { id: "maths-quadratic-equation-and-inequalities-c3", name: "Quadratic inequalities & wavy curve method", done: false, weight: "High" },
        { id: "maths-quadratic-equation-and-inequalities-c4", name: "Location of roots relative to values", done: false, weight: "High" },
      ]},
      { id: "maths-sequence-and-series", trackId: "maths", name: "Sequence and Series", priority: "High", completion: 0, concepts: [
        { id: "maths-sequence-and-series-c1", name: "AP — nth term & sum formulas", done: false, weight: "High" },
        { id: "maths-sequence-and-series-c2", name: "GP — nth term, sum, infinite GP", done: false, weight: "High" },
        { id: "maths-sequence-and-series-c3", name: "HP & AM-GM-HM inequality", done: false, weight: "High" },
        { id: "maths-sequence-and-series-c4", name: "Telescoping & method of differences", done: false, weight: "Medium" },
      ]},
      { id: "maths-trigonometric-equations-and-inequalities", trackId: "maths", name: "Trigonometric Equations and Inequalities", priority: "High", completion: 0, concepts: [
        { id: "maths-trigonometric-equations-and-inequalities-c1", name: "General solutions of sin, cos, tan equations", done: false, weight: "High" },
        { id: "maths-trigonometric-equations-and-inequalities-c2", name: "Trigonometric inequalities", done: false, weight: "High" },
        { id: "maths-trigonometric-equations-and-inequalities-c3", name: "Equations of the form asinx + bcosx = c", done: false, weight: "High" },
      ]},
      { id: "maths-solution-of-triangle", trackId: "maths", name: "Solution of Triangle", priority: "High", completion: 0, concepts: [
        { id: "maths-solution-of-triangle-c1", name: "Sine rule & cosine rule", done: false, weight: "High" },
        { id: "maths-solution-of-triangle-c2", name: "Area of triangle & Hero's formula", done: false, weight: "High" },
        { id: "maths-solution-of-triangle-c3", name: "Circumradius, inradius & ex-radii", done: false, weight: "High" },
      ]},
      { id: "maths-straight-lines", trackId: "maths", name: "Straight Lines", priority: "High", completion: 0, concepts: [
        { id: "maths-straight-lines-c1", name: "Equations of a line — all forms", done: false, weight: "High" },
        { id: "maths-straight-lines-c2", name: "Angle between lines & perpendicular distance", done: false, weight: "High" },
        { id: "maths-straight-lines-c3", name: "Pair of straight lines", done: false, weight: "High" },
        { id: "maths-straight-lines-c4", name: "Locus problems", done: false, weight: "Medium" },
      ]},
      { id: "maths-circles", trackId: "maths", name: "Circles", priority: "High", completion: 0, concepts: [
        { id: "maths-circles-c1", name: "Equation of circle — standard & general form", done: false, weight: "High" },
        { id: "maths-circles-c2", name: "Tangent & normal to a circle", done: false, weight: "High" },
        { id: "maths-circles-c3", name: "Chord of contact & family of circles", done: false, weight: "High" },
        { id: "maths-circles-c4", name: "Radical axis & coaxial circles", done: false, weight: "Medium" },
      ]},
      { id: "maths-parabola", trackId: "maths", name: "Parabola", priority: "High", completion: 0, concepts: [
        { id: "maths-parabola-c1", name: "Standard forms — y²=4ax, x²=4ay", done: false, weight: "High" },
        { id: "maths-parabola-c2", name: "Tangent, normal & chord of contact", done: false, weight: "High" },
        { id: "maths-parabola-c3", name: "Parametric form & chord joining two points", done: false, weight: "High" },
      ]},
      { id: "maths-ellipse", trackId: "maths", name: "Ellipse", priority: "High", completion: 0, concepts: [
        { id: "maths-ellipse-c1", name: "Equation, eccentricity, foci & directrix", done: false, weight: "High" },
        { id: "maths-ellipse-c2", name: "Tangent & normal to ellipse", done: false, weight: "High" },
        { id: "maths-ellipse-c3", name: "Auxiliary circle & eccentric angle", done: false, weight: "Medium" },
      ]},
      { id: "maths-hyperbola", trackId: "maths", name: "Hyperbola", priority: "High", completion: 0, concepts: [
        { id: "maths-hyperbola-c1", name: "Equation, eccentricity, foci & asymptotes", done: false, weight: "High" },
        { id: "maths-hyperbola-c2", name: "Rectangular hyperbola — xy = c²", done: false, weight: "High" },
        { id: "maths-hyperbola-c3", name: "Tangent & normal to hyperbola", done: false, weight: "High" },
      ]},
      { id: "maths-permutations-and-combinations", trackId: "maths", name: "Permutations and Combinations", priority: "High", completion: 0, concepts: [
        { id: "maths-permutations-and-combinations-c1", name: "Fundamental counting principle", done: false, weight: "High" },
        { id: "maths-permutations-and-combinations-c2", name: "Permutations with & without repetition", done: false, weight: "High" },
        { id: "maths-permutations-and-combinations-c3", name: "Combinations & selection problems", done: false, weight: "High" },
        { id: "maths-permutations-and-combinations-c4", name: "Circular permutations & multinomial theorem", done: false, weight: "Medium" },
      ]},
      { id: "maths-binomial-theorem", trackId: "maths", name: "Binomial Theorem", priority: "High", completion: 0, concepts: [
        { id: "maths-binomial-theorem-c1", name: "Binomial expansion & general term", done: false, weight: "High" },
        { id: "maths-binomial-theorem-c2", name: "Finding specific terms & coefficients", done: false, weight: "High" },
        { id: "maths-binomial-theorem-c3", name: "Middle term & greatest coefficient", done: false, weight: "High" },
        { id: "maths-binomial-theorem-c4", name: "Multinomial expansion", done: false, weight: "Medium" },
      ]},
      { id: "maths-determinant", trackId: "maths", name: "Determinant", priority: "High", completion: 0, concepts: [
        { id: "maths-determinant-c1", name: "Expansion of 2×2 & 3×3 determinants", done: false, weight: "High" },
        { id: "maths-determinant-c2", name: "Properties of determinants", done: false, weight: "High" },
        { id: "maths-determinant-c3", name: "System of equations — Cramer's rule", done: false, weight: "High" },
        { id: "maths-determinant-c4", name: "Area of triangle using determinant", done: false, weight: "Medium" },
      ]},
      { id: "maths-relation", trackId: "maths", name: "Relation", priority: "Medium", completion: 0, concepts: [
        { id: "maths-relation-c1", name: "Types of relations — reflexive, symmetric, transitive", done: false, weight: "High" },
        { id: "maths-relation-c2", name: "Equivalence relation", done: false, weight: "High" },
      ]},
      { id: "maths-function", trackId: "maths", name: "Function", priority: "High", completion: 0, concepts: [
        { id: "maths-function-c1", name: "Domain, range & codomain", done: false, weight: "High" },
        { id: "maths-function-c2", name: "Types — injective, surjective, bijective", done: false, weight: "High" },
        { id: "maths-function-c3", name: "Composition & inverse of functions", done: false, weight: "High" },
        { id: "maths-function-c4", name: "Even, odd, periodic functions", done: false, weight: "High" },
      ]},
      { id: "maths-itf", trackId: "maths", name: "ITF", priority: "High", completion: 0, concepts: [
        { id: "maths-itf-c1", name: "Domain & range of inverse trig functions", done: false, weight: "High" },
        { id: "maths-itf-c2", name: "Principal value branches", done: false, weight: "High" },
        { id: "maths-itf-c3", name: "Key identities — sin⁻¹x + cos⁻¹x = π/2 etc.", done: false, weight: "High" },
        { id: "maths-itf-c4", name: "ITF equations & simplification", done: false, weight: "High" },
      ]},
      { id: "maths-limits", trackId: "maths", name: "LIMITS", priority: "High", completion: 0, concepts: [
        { id: "maths-limits-c1", name: "Standard limits & L'Hôpital's rule", done: false, weight: "High" },
        { id: "maths-limits-c2", name: "Sandwich theorem", done: false, weight: "Medium" },
        { id: "maths-limits-c3", name: "Left & right hand limits", done: false, weight: "High" },
        { id: "maths-limits-c4", name: "Limits involving exponential & logarithmic forms", done: false, weight: "High" },
      ]},
      { id: "maths-continuity", trackId: "maths", name: "Continuity", priority: "High", completion: 0, concepts: [
        { id: "maths-continuity-c1", name: "Continuity at a point & on an interval", done: false, weight: "High" },
        { id: "maths-continuity-c2", name: "Types of discontinuity — removable, jump, infinite", done: false, weight: "High" },
        { id: "maths-continuity-c3", name: "Intermediate value theorem", done: false, weight: "Medium" },
      ]},
      { id: "maths-differentiability", trackId: "maths", name: "Differentiability", priority: "High", completion: 0, concepts: [
        { id: "maths-differentiability-c1", name: "LHD & RHD — differentiability check", done: false, weight: "High" },
        { id: "maths-differentiability-c2", name: "Non-differentiable points — corner, cusp, vertical tangent", done: false, weight: "High" },
        { id: "maths-differentiability-c3", name: "Relation between continuity & differentiability", done: false, weight: "High" },
      ]},
      { id: "maths-mod", trackId: "maths", name: "MOD", priority: "High", completion: 0, concepts: [
        { id: "maths-mod-c1", name: "Chain rule & product rule", done: false, weight: "High" },
        { id: "maths-mod-c2", name: "Implicit differentiation", done: false, weight: "High" },
        { id: "maths-mod-c3", name: "Parametric & higher order derivatives", done: false, weight: "High" },
        { id: "maths-mod-c4", name: "Differentiation of logarithmic functions", done: false, weight: "High" },
      ]},
      { id: "maths-aod", trackId: "maths", name: "AOD", priority: "High", completion: 0, concepts: [
        { id: "maths-aod-c1", name: "Tangent & normal to a curve", done: false, weight: "High" },
        { id: "maths-aod-c2", name: "Monotonicity — increasing/decreasing intervals", done: false, weight: "High" },
        { id: "maths-aod-c3", name: "Maxima & minima (first/second derivative test)", done: false, weight: "High" },
        { id: "maths-aod-c4", name: "Rolle's & mean value theorems", done: false, weight: "High" },
      ]},
      { id: "maths-indefinite-integration", trackId: "maths", name: "Indefinite Integration", priority: "High", completion: 0, concepts: [
        { id: "maths-indefinite-integration-c1", name: "Standard integrals & substitution method", done: false, weight: "High" },
        { id: "maths-indefinite-integration-c2", name: "Integration by parts (ILATE)", done: false, weight: "High" },
        { id: "maths-indefinite-integration-c3", name: "Partial fractions", done: false, weight: "High" },
        { id: "maths-indefinite-integration-c4", name: "Special integrals — rational trig functions", done: false, weight: "High" },
      ]},
      { id: "maths-definite-integration", trackId: "maths", name: "Definite Integration", priority: "High", completion: 0, concepts: [
        { id: "maths-definite-integration-c1", name: "Newton-Leibniz theorem", done: false, weight: "High" },
        { id: "maths-definite-integration-c2", name: "Properties of definite integrals", done: false, weight: "High" },
        { id: "maths-definite-integration-c3", name: "Gamma function & Walli's formula", done: false, weight: "Medium" },
        { id: "maths-definite-integration-c4", name: "Definite integration as limit of sum", done: false, weight: "High" },
      ]},
      { id: "maths-area-under-curve", trackId: "maths", name: "AREA UNDER CURVE", priority: "High", completion: 0, concepts: [
        { id: "maths-area-under-curve-c1", name: "Area between curve & x-axis", done: false, weight: "High" },
        { id: "maths-area-under-curve-c2", name: "Area between two curves", done: false, weight: "High" },
        { id: "maths-area-under-curve-c3", name: "Area with parametric & polar curves", done: false, weight: "Medium" },
      ]},
      { id: "maths-differential-equation", trackId: "maths", name: "Differential Equation", priority: "High", completion: 0, concepts: [
        { id: "maths-differential-equation-c1", name: "Variable separable method", done: false, weight: "High" },
        { id: "maths-differential-equation-c2", name: "Homogeneous differential equations", done: false, weight: "High" },
        { id: "maths-differential-equation-c3", name: "Linear first-order ODE (integrating factor)", done: false, weight: "High" },
      ]},
      { id: "maths-matrices", trackId: "maths", name: "Matrices", priority: "High", completion: 0, concepts: [
        { id: "maths-matrices-c1", name: "Matrix operations & special matrices", done: false, weight: "High" },
        { id: "maths-matrices-c2", name: "Transpose, adjoint & inverse of a matrix", done: false, weight: "High" },
        { id: "maths-matrices-c3", name: "Elementary row operations", done: false, weight: "Medium" },
      ]},
      { id: "maths-vector", trackId: "maths", name: "Vector", priority: "High", completion: 0, concepts: [
        { id: "maths-vector-c1", name: "Dot product & cross product", done: false, weight: "High" },
        { id: "maths-vector-c2", name: "Scalar triple product & coplanarity", done: false, weight: "High" },
        { id: "maths-vector-c3", name: "Vector equations of lines & planes", done: false, weight: "High" },
      ]},
      { id: "maths-3d", trackId: "maths", name: "3D", priority: "High", completion: 0, concepts: [
        { id: "maths-3d-c1", name: "Direction cosines & direction ratios", done: false, weight: "High" },
        { id: "maths-3d-c2", name: "Line in 3D — symmetric & parametric form", done: false, weight: "High" },
        { id: "maths-3d-c3", name: "Plane — equation, angle, distance", done: false, weight: "High" },
        { id: "maths-3d-c4", name: "Distance between skew lines", done: false, weight: "High" },
      ]},
      { id: "maths-probability", trackId: "maths", name: "Probability", priority: "High", completion: 0, concepts: [
        { id: "maths-probability-c1", name: "Classical probability & counting", done: false, weight: "High" },
        { id: "maths-probability-c2", name: "Conditional probability & Bayes' theorem", done: false, weight: "High" },
        { id: "maths-probability-c3", name: "Independent events & multiplication theorem", done: false, weight: "High" },
        { id: "maths-probability-c4", name: "Binomial distribution", done: false, weight: "High" },
      ]},
      { id: "maths-complex-number", trackId: "maths", name: "Complex Number", priority: "High", completion: 0, concepts: [
        { id: "maths-complex-number-c1", name: "Argand plane, modulus & argument", done: false, weight: "High" },
        { id: "maths-complex-number-c2", name: "Polar form & Euler's formula", done: false, weight: "High" },
        { id: "maths-complex-number-c3", name: "De Moivre's theorem & nth roots of unity", done: false, weight: "High" },
        { id: "maths-complex-number-c4", name: "Geometry of complex numbers (loci)", done: false, weight: "High" },
      ]},
    ],
  },
];
