import type { Track } from "./store";

export const SEED_TRACKS: Track[] = [
  {
    id: "physics",
    name: "Physics",
    chapters: [
      { id: "phy-1", trackId: "physics", name: "Kinematics", priority: "High", completion: 0 },
      { id: "phy-2", trackId: "physics", name: "Laws of Motion", priority: "High", completion: 0 },
      { id: "phy-3", trackId: "physics", name: "Rotational Motion", priority: "High", completion: 0 },
      { id: "phy-4", trackId: "physics", name: "Gravitation", priority: "Medium", completion: 0 },
      { id: "phy-5", trackId: "physics", name: "Thermodynamics", priority: "High", completion: 0 },
      { id: "phy-6", trackId: "physics", name: "Electrostatics", priority: "High", completion: 0 },
      { id: "phy-7", trackId: "physics", name: "Current Electricity", priority: "High", completion: 0 },
      { id: "phy-8", trackId: "physics", name: "Magnetism & EMI", priority: "High", completion: 0 },
      { id: "phy-9", trackId: "physics", name: "Optics", priority: "Medium", completion: 0 },
      { id: "phy-10", trackId: "physics", name: "Modern Physics", priority: "High", completion: 0 },
      { id: "phy-11", trackId: "physics", name: "Waves & SHM", priority: "Medium", completion: 0 },
    ],
  },
  {
    id: "pchem",
    name: "Physical Chemistry",
    chapters: [
      { id: "pc-1", trackId: "pchem", name: "Mole Concept", priority: "High", completion: 0 },
      { id: "pc-2", trackId: "pchem", name: "Atomic Structure", priority: "High", completion: 0 },
      { id: "pc-3", trackId: "pchem", name: "Thermodynamics", priority: "High", completion: 0 },
      { id: "pc-4", trackId: "pchem", name: "Chemical Equilibrium", priority: "High", completion: 0 },
      { id: "pc-5", trackId: "pchem", name: "Ionic Equilibrium", priority: "High", completion: 0 },
      { id: "pc-6", trackId: "pchem", name: "Electrochemistry", priority: "High", completion: 0 },
      { id: "pc-7", trackId: "pchem", name: "Chemical Kinetics", priority: "Medium", completion: 0 },
      { id: "pc-8", trackId: "pchem", name: "Solutions", priority: "Medium", completion: 0 },
    ],
  },
  {
    id: "ochem",
    name: "Organic Chemistry",
    chapters: [
      { id: "oc-1", trackId: "ochem", name: "GOC & Isomerism", priority: "High", completion: 0 },
      { id: "oc-2", trackId: "ochem", name: "Hydrocarbons", priority: "High", completion: 0 },
      { id: "oc-3", trackId: "ochem", name: "Haloalkanes & Haloarenes", priority: "High", completion: 0 },
      { id: "oc-4", trackId: "ochem", name: "Alcohols, Phenols, Ethers", priority: "High", completion: 0 },
      { id: "oc-5", trackId: "ochem", name: "Aldehydes & Ketones", priority: "High", completion: 0 },
      { id: "oc-6", trackId: "ochem", name: "Carboxylic Acids", priority: "Medium", completion: 0 },
      { id: "oc-7", trackId: "ochem", name: "Amines", priority: "High", completion: 0 },
      { id: "oc-8", trackId: "ochem", name: "Biomolecules & Polymers", priority: "Medium", completion: 0 },
    ],
  },
  {
    id: "ichem",
    name: "Inorganic Chemistry",
    chapters: [
      { id: "ic-1", trackId: "ichem", name: "Chemical Bonding", priority: "High", completion: 0 },
      { id: "ic-2", trackId: "ichem", name: "Periodic Table", priority: "High", completion: 0 },
      { id: "ic-3", trackId: "ichem", name: "Coordination Compounds", priority: "High", completion: 0 },
      { id: "ic-4", trackId: "ichem", name: "p-Block Elements", priority: "High", completion: 0 },
      { id: "ic-5", trackId: "ichem", name: "d & f-Block Elements", priority: "Medium", completion: 0 },
      { id: "ic-6", trackId: "ichem", name: "s-Block Elements", priority: "Medium", completion: 0 },
      { id: "ic-7", trackId: "ichem", name: "Qualitative Analysis", priority: "High", completion: 0 },
    ],
  },
  {
    id: "maths",
    name: "Mathematics",
    chapters: [
      { id: "m-1", trackId: "maths", name: "Quadratic Equations", priority: "Medium", completion: 0 },
      { id: "m-2", trackId: "maths", name: "Sequences & Series", priority: "Medium", completion: 0 },
      { id: "m-3", trackId: "maths", name: "Trigonometry", priority: "High", completion: 0 },
      { id: "m-4", trackId: "maths", name: "Coordinate Geometry", priority: "High", completion: 0 },
      { id: "m-5", trackId: "maths", name: "Conic Sections", priority: "High", completion: 0 },
      { id: "m-6", trackId: "maths", name: "Limits, Continuity, Differentiability", priority: "High", completion: 0 },
      { id: "m-7", trackId: "maths", name: "Application of Derivatives", priority: "High", completion: 0 },
      { id: "m-8", trackId: "maths", name: "Integrals & Area", priority: "High", completion: 0 },
      { id: "m-9", trackId: "maths", name: "Differential Equations", priority: "Medium", completion: 0 },
      { id: "m-10", trackId: "maths", name: "Vectors & 3D Geometry", priority: "High", completion: 0 },
      { id: "m-11", trackId: "maths", name: "Probability", priority: "High", completion: 0 },
      { id: "m-12", trackId: "maths", name: "Matrices & Determinants", priority: "Medium", completion: 0 },
      { id: "m-13", trackId: "maths", name: "Complex Numbers", priority: "Medium", completion: 0 },
    ],
  },
];
