/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as TeachTestRouteImport } from './routes/teach-test'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as NavTestRouteImport } from './routes/nav-test'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as LogRouteImport } from './routes/log'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as CommunityNotesRouteImport } from './routes/community-notes'
import { Route as AirgapRouteImport } from './routes/airgap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestTestIdRouteImport } from './routes/test.$testId'
import { Route as TestResultsTestIdRouteImport } from './routes/test-results.$testId'
import { Route as PracticeSessionIdRouteImport } from './routes/practice.$sessionId'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminReviewJobIdRouteImport } from './routes/admin/review.$jobId'
import { Route as AdminReviewRouteImport } from './routes/admin/review.'

const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachTestRoute = TeachTestRouteImport.update({
  id: '/teach-test',
  path: '/teach-test',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const NavTestRoute = NavTestRouteImport.update({
  id: '/nav-test',
  path: '/nav-test',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityNotesRoute = CommunityNotesRouteImport.update({
  id: '/community-notes',
  path: '/community-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const AirgapRoute = AirgapRouteImport.update({
  id: '/airgap',
  path: '/airgap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestTestIdRoute = TestTestIdRouteImport.update({
  id: '/test/$testId',
  path: '/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestResultsTestIdRoute = TestResultsTestIdRouteImport.update({
  id: '/test-results/$testId',
  path: '/test-results/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeSessionIdRoute = PracticeSessionIdRouteImport.update({
  id: '/practice/$sessionId',
  path: '/practice/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewJobIdRoute = AdminReviewJobIdRouteImport.update({
  id: '/admin/review/$jobId',
  path: '/admin/review/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewRoute = AdminReviewRouteImport.update({
  id: '/admin/review/',
  path: '/admin/review/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/community-notes': typeof CommunityNotesRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/nav-test': typeof NavTestRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/problems': typeof ProblemsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/teach-test': typeof TeachTestRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/practice/$sessionId': typeof PracticeSessionIdRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/admin/review/': typeof AdminReviewRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/community-notes': typeof CommunityNotesRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/nav-test': typeof NavTestRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/problems': typeof ProblemsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/teach-test': typeof TeachTestRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/practice/$sessionId': typeof PracticeSessionIdRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/admin/review': typeof AdminReviewRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/community-notes': typeof CommunityNotesRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/nav-test': typeof NavTestRoute
  '/notes': typeof NotesRoute
  '/privacy': typeof PrivacyRoute
  '/problems': typeof ProblemsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/teach-test': typeof TeachTestRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/practice/$sessionId': typeof PracticeSessionIdRoute
  '/test-results/$testId': typeof TestResultsTestIdRoute
  '/test/$testId': typeof TestTestIdRoute
  '/admin/review/': typeof AdminReviewRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airgap'
    | '/community-notes'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/nav-test'
    | '/notes'
    | '/privacy'
    | '/problems'
    | '/sitemap.xml'
    | '/teach'
    | '/teach-test'
    | '/tracks'
    | '/admin/upload'
    | '/practice/$sessionId'
    | '/test-results/$testId'
    | '/test/$testId'
    | '/admin/review/'
    | '/admin/review/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airgap'
    | '/community-notes'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/nav-test'
    | '/notes'
    | '/privacy'
    | '/problems'
    | '/sitemap.xml'
    | '/teach'
    | '/teach-test'
    | '/tracks'
    | '/admin/upload'
    | '/practice/$sessionId'
    | '/test-results/$testId'
    | '/test/$testId'
    | '/admin/review'
    | '/admin/review/$jobId'
  id:
    | '__root__'
    | '/'
    | '/airgap'
    | '/community-notes'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/nav-test'
    | '/notes'
    | '/privacy'
    | '/problems'
    | '/sitemap.xml'
    | '/teach'
    | '/teach-test'
    | '/tracks'
    | '/admin/upload'
    | '/practice/$sessionId'
    | '/test-results/$testId'
    | '/test/$testId'
    | '/admin/review/'
    | '/admin/review/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirgapRoute: typeof AirgapRoute
  CommunityNotesRoute: typeof CommunityNotesRoute
  FocusRoute: typeof FocusRoute
  LogRoute: typeof LogRoute
  MatrixRoute: typeof MatrixRoute
  NavTestRoute: typeof NavTestRoute
  NotesRoute: typeof NotesRoute
  PrivacyRoute: typeof PrivacyRoute
  ProblemsRoute: typeof ProblemsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachRoute: typeof TeachRoute
  TeachTestRoute: typeof TeachTestRoute
  TracksRoute: typeof TracksRoute
  AdminUploadRoute: typeof AdminUploadRoute
  PracticeSessionIdRoute: typeof PracticeSessionIdRoute
  TestResultsTestIdRoute: typeof TestResultsTestIdRoute
  TestTestIdRoute: typeof TestTestIdRoute
  AdminReviewRoute: typeof AdminReviewRoute
  AdminReviewJobIdRoute: typeof AdminReviewJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach-test': {
      id: '/teach-test'
      path: '/teach-test'
      fullPath: '/teach-test'
      preLoaderRoute: typeof TeachTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nav-test': {
      id: '/nav-test'
      path: '/nav-test'
      fullPath: '/nav-test'
      preLoaderRoute: typeof NavTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-notes': {
      id: '/community-notes'
      path: '/community-notes'
      fullPath: '/community-notes'
      preLoaderRoute: typeof CommunityNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airgap': {
      id: '/airgap'
      path: '/airgap'
      fullPath: '/airgap'
      preLoaderRoute: typeof AirgapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$testId': {
      id: '/test/$testId'
      path: '/test/$testId'
      fullPath: '/test/$testId'
      preLoaderRoute: typeof TestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-results/$testId': {
      id: '/test-results/$testId'
      path: '/test-results/$testId'
      fullPath: '/test-results/$testId'
      preLoaderRoute: typeof TestResultsTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$sessionId': {
      id: '/practice/$sessionId'
      path: '/practice/$sessionId'
      fullPath: '/practice/$sessionId'
      preLoaderRoute: typeof PracticeSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review/$jobId': {
      id: '/admin/review/$jobId'
      path: '/admin/review/$jobId'
      fullPath: '/admin/review/$jobId'
      preLoaderRoute: typeof AdminReviewJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review/': {
      id: '/admin/review/'
      path: '/admin/review'
      fullPath: '/admin/review/'
      preLoaderRoute: typeof AdminReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirgapRoute: AirgapRoute,
  CommunityNotesRoute: CommunityNotesRoute,
  FocusRoute: FocusRoute,
  LogRoute: LogRoute,
  MatrixRoute: MatrixRoute,
  NavTestRoute: NavTestRoute,
  NotesRoute: NotesRoute,
  PrivacyRoute: PrivacyRoute,
  ProblemsRoute: ProblemsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachRoute: TeachRoute,
  TeachTestRoute: TeachTestRoute,
  TracksRoute: TracksRoute,
  AdminUploadRoute: AdminUploadRoute,
  PracticeSessionIdRoute: PracticeSessionIdRoute,
  TestResultsTestIdRoute: TestResultsTestIdRoute,
  TestTestIdRoute: TestTestIdRoute,
  AdminReviewRoute: AdminReviewRoute,
  AdminReviewJobIdRoute: AdminReviewJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
