/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as TeachRouteImport } from './routes/teach'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as MatrixRouteImport } from './routes/matrix'
import { Route as LogRouteImport } from './routes/log'
import { Route as FocusRouteImport } from './routes/focus'
import { Route as AirgapRouteImport } from './routes/airgap'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as AdminReviewJobIdRouteImport } from './routes/admin/review.$jobId'

const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachRoute = TeachRouteImport.update({
  id: '/teach',
  path: '/teach',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const MatrixRoute = MatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => rootRouteImport,
} as any)
const LogRoute = LogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => rootRouteImport,
} as any)
const FocusRoute = FocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => rootRouteImport,
} as any)
const AirgapRoute = AirgapRouteImport.update({
  id: '/airgap',
  path: '/airgap',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/admin/upload',
  path: '/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewJobIdRoute = AdminReviewJobIdRouteImport.update({
  id: '/admin/review/$jobId',
  path: '/admin/review/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/airgap': typeof AirgapRoute
  '/focus': typeof FocusRoute
  '/log': typeof LogRoute
  '/matrix': typeof MatrixRoute
  '/notes': typeof NotesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/teach': typeof TeachRoute
  '/tracks': typeof TracksRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/review/$jobId': typeof AdminReviewJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/airgap'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/notes'
    | '/sitemap.xml'
    | '/teach'
    | '/tracks'
    | '/admin/upload'
    | '/admin/review/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/airgap'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/notes'
    | '/sitemap.xml'
    | '/teach'
    | '/tracks'
    | '/admin/upload'
    | '/admin/review/$jobId'
  id:
    | '__root__'
    | '/'
    | '/airgap'
    | '/focus'
    | '/log'
    | '/matrix'
    | '/notes'
    | '/sitemap.xml'
    | '/teach'
    | '/tracks'
    | '/admin/upload'
    | '/admin/review/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AirgapRoute: typeof AirgapRoute
  FocusRoute: typeof FocusRoute
  LogRoute: typeof LogRoute
  MatrixRoute: typeof MatrixRoute
  NotesRoute: typeof NotesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeachRoute: typeof TeachRoute
  TracksRoute: typeof TracksRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminReviewJobIdRoute: typeof AdminReviewJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teach': {
      id: '/teach'
      path: '/teach'
      fullPath: '/teach'
      preLoaderRoute: typeof TeachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matrix': {
      id: '/matrix'
      path: '/matrix'
      fullPath: '/matrix'
      preLoaderRoute: typeof MatrixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/log': {
      id: '/log'
      path: '/log'
      fullPath: '/log'
      preLoaderRoute: typeof LogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/focus': {
      id: '/focus'
      path: '/focus'
      fullPath: '/focus'
      preLoaderRoute: typeof FocusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airgap': {
      id: '/airgap'
      path: '/airgap'
      fullPath: '/airgap'
      preLoaderRoute: typeof AirgapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/admin/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/review/$jobId': {
      id: '/admin/review/$jobId'
      path: '/admin/review/$jobId'
      fullPath: '/admin/review/$jobId'
      preLoaderRoute: typeof AdminReviewJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AirgapRoute: AirgapRoute,
  FocusRoute: FocusRoute,
  LogRoute: LogRoute,
  MatrixRoute: MatrixRoute,
  NotesRoute: NotesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeachRoute: TeachRoute,
  TracksRoute: TracksRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminReviewJobIdRoute: AdminReviewJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
